import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {valueFromRating,ratingFromValue,points,defaultConfig,rankPlayers,evaluateTrade,bestLineup,scoringWarnings,configSchema,pickValue} from '../lib/football.ts';
const data=JSON.parse(fs.readFileSync(new URL('../data/catalog.json',import.meta.url)));
const ranked=rankPlayers(data.players,defaultConfig);
test('display curve preserves inverse and elite premium',()=>{for(const r of [1,2,20,50,80,100])assert.ok(Math.abs(ratingFromValue(valueFromRating(r))-r)<1e-9);assert.ok(50*valueFromRating(2)<valueFromRating(100)*.05);});
test('PPR, passing, fumbles, and TE premium use raw stats',()=>{const s={passing_yards:250,passing_tds:2,passing_interceptions:1,receptions:5,receiving_yards:60,fumbles_lost_total:1};assert.equal(points(s,'WR',defaultConfig),25);assert.equal(points(s,'TE',{...defaultConfig,tep:1}),30);assert.equal(points(s,'WR',{...defaultConfig,ppr:0}),20);});
test('unsupported scoring is disclosed and bad configurations rejected',()=>{assert.equal(scoringWarnings({bonus_pass_yd_300:3}).length,1);assert.equal(scoringWarnings({rec:1,bonus_rec_te:.5}).length,0);assert.equal(configSchema.safeParse({teams:-3}).success,false);});

test('standard Sleeper kicker and team-defense rules do not create offensive warnings',()=>{
 const excluded={sack:1,fgm_40_49:4,pts_allow_0:10,fgm_30_39:3,fgm_50_59:5,xpmiss:-1,fgmiss:-1,ff:1,pts_allow_14_20:1,fgm_0_19:3,int:2,def_st_fum_rec:1,pts_allow_1_6:7,fgm_60p:6,fgm_20_29:3,xpm:1,fum_rec:2,def_st_td:6,def_td:6,safe:2,blk_kick:2,pts_allow_28_34:-1,pts_allow_35p:-4,def_st_ff:1,pts_allow_7_13:4};
 assert.deepEqual(scoringWarnings({...excluded,rec:1,pass_int:-1}),[]);
 const messages=scoringWarnings({...excluded,st_td:6,st_fum_rec:1,st_ff:1,fum_rec_td:6});
 assert.equal(messages.length,1);assert.match(messages[0],/special-teams touchdowns/);assert.match(messages[0],/fumble-recovery touchdowns/);assert.doesNotMatch(messages[0],/fgm_|pts_allow_|def_st_/);
 assert.equal(points({passing_interceptions:2,receptions:3},'WR',{...defaultConfig,scoring:{...excluded,pass_int:-1,rec:1}}),1);
});
test('rankings are bounded, finite, deterministic and preserve every player',()=>{assert.equal(ranked.length,data.players.length);assert.ok(ranked.every(p=>Number.isFinite(p.value)&&p.rating>=1&&p.rating<=100));assert.equal(JSON.stringify(ranked),JSON.stringify(rankPlayers(data.players,defaultConfig)));});
test('superflex increases scarcity value for an established QB',()=>{const q=ranked.find(p=>p.name==='Josh Allen');const sf=rankPlayers(data.players,{...defaultConfig,superflex:true}).find(p=>p.id===q.id);assert.ok(sf.value>q.value);});
test('lineup optimizer reserves eligible positional slots',()=>{const p=(id,pos,ppg)=>({id,position:pos,ppg});assert.equal(bestLineup([p('a','QB',30),p('b','WR',25),p('c','QB',10)],['SUPER_FLEX','QB']),55);assert.equal(bestLineup([p('a','QB',30)],['QB','SUPER_FLEX']),30);});
test('trade sides swap symmetrically',()=>{const sides=[[{kind:'player',id:ranked[0].id}],[{kind:'player',id:ranked[6].id}]];const a=evaluateTrade(sides,ranked,defaultConfig,2027),b=evaluateTrade([sides[1],sides[0]],ranked,defaultConfig,2027);assert.equal(a.gap,-b.gap);assert.equal(a.sides[0].net,b.sides[1].net);});
test('equal value assets have no edge; duplicates and missing assets reject',()=>{const r=[{...ranked[0],id:'a',value:100},{...ranked[0],id:'b',value:100}];assert.equal(evaluateTrade([[{kind:'player',id:'a'}],[{kind:'player',id:'b'}]],r,defaultConfig,2027).gap,0);assert.throws(()=>evaluateTrade([[{kind:'player',id:'a'}],[{kind:'player',id:'a'}]],r,defaultConfig,2027),/same asset/);assert.throws(()=>evaluateTrade([[{kind:'player',id:'nope'}],[{kind:'player',id:'b'}]],r,defaultConfig,2027),/Unknown/);});
test('roster expansion cuts lowest retained assets and accounts for waiver pickups',()=>{const r=[{...ranked[0],id:'elite',value:1000,ppg:20},{...ranked[0],id:'a',value:300,ppg:10},{...ranked[0],id:'b',value:250,ppg:8},{...ranked[0],id:'bench',value:50,ppg:2},{...ranked[0],id:'free',value:10,ppg:1}];const ctx={rosters:[['elite','bench'],['a','b']],available:['free'],capacity:2};const t=evaluateTrade([[{kind:'player',id:'elite'}],[{kind:'player',id:'a'},{kind:'player',id:'b'}]],r,defaultConfig,2027,ctx);assert.equal(t.sides[0].cuts[0].id,'bench');assert.equal(t.sides[1].pickups[0].id,'free');});
test('fifty marginal players cannot equal an elite and roster capacity is bounded',()=>{const elite={...ranked[0],id:'elite',value:valueFromRating(100)},weak=Array.from({length:50},(_,i)=>({...ranked[0],id:'w'+i,value:valueFromRating(2),ppg:1}));const t=evaluateTrade([[{kind:'player',id:'elite'}],weak.map(p=>({kind:'player',id:p.id}))],[elite,...weak],defaultConfig,2027);assert.ok(t.sides[0].net< -9000);assert.equal(t.sides[0].cuts.length,25);});
test('pick chronology and slot bounds are validated',()=>{assert.throws(()=>pickValue({kind:'pick',year:2026,round:1,slot:'early'},defaultConfig,2027),/next three/);assert.throws(()=>pickValue({kind:'pick',year:2027,round:1,slot:13},defaultConfig,2027),/league size/);assert.ok(pickValue({kind:'pick',year:2027,round:1,slot:1},defaultConfig,2027)>pickValue({kind:'pick',year:2029,round:1,slot:1},defaultConfig,2027));});
