'use client';
import { useEffect,useMemo,useState } from 'react';
import { Search,X,Plus } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Table,TableHeader,TableBody,TableRow,TableHead,TableCell } from '@/components/ui/table';
import { type Config,type Manifest,type SeasonStats,points } from '@/lib/football';
import { api,Choice,fmt,Pos } from './ui-support';
export function History({config,manifest,initial}:{config:Config;manifest:Manifest;initial:{id:string;season:number}|null}){
 const [season,setSeason]=useState(String(initial?.season??manifest.season)),[entries,setEntries]=useState<SeasonStats[]>([]),[selected,setSelected]=useState<SeasonStats[]>([]),[q,setQ]=useState(''),[error,setError]=useState(''),[mode,setMode]=useState('all'),[busy,setBusy]=useState(false);
 useEffect(()=>{if(initial)setSeason(String(initial.season));},[initial]);
 useEffect(()=>{const c=new AbortController();setBusy(true);setError('');api<SeasonStats[]>(`/api/history/${season}`,undefined,c.signal).then(d=>{setEntries(d);if(initial&&initial.season===Number(season)){const p=d.find(x=>x.id===initial.id);if(p)setSelected(prev=>prev.some(x=>x.id===p.id&&x.season===p.season)?prev:[...prev,p].slice(-4));}}).catch(e=>{if(!c.signal.aborted)setError(e.message);}).finally(()=>{if(!c.signal.aborted)setBusy(false);});return()=>c.abort();},[season,initial]);
 const candidates=useMemo(()=>entries.filter(e=>`${e.name} ${e.team}`.toLowerCase().includes(q.toLowerCase())&&(mode==='all'||!selected.length||(e.position===selected[0].position&&(mode==='age'?e.age!==null&&selected[0].age!==null&&Math.abs(e.age-selected[0].age)<1:e.careerYear===selected[0].careerYear)))).sort((a,b)=>points(b.stats,b.position,config)/b.games-points(a.stats,a.position,config)/a.games).slice(0,30),[entries,q,mode,selected,config]);
 const add=(e:SeasonStats)=>{if(selected.length<4&&!selected.some(s=>s.id===e.id&&s.season===e.season))setSelected([...selected,e]);};
 const metrics:[string,(s:SeasonStats)=>number|null][]=[['Age',s=>s.age],['Career year',s=>s.careerYear],['Statistical games',s=>s.games],['Fantasy points / game',s=>points(s.stats,s.position,config)/s.games],['Position percentile (PPR)',s=>s.percentile],['Targets / game',s=>s.stats.targets==null?null:s.stats.targets/s.games],['Receptions / game',s=>s.stats.receptions==null?null:s.stats.receptions/s.games],['Receiving yards / game',s=>s.stats.receiving_yards==null?null:s.stats.receiving_yards/s.games],['Carries / game',s=>s.stats.carries==null?null:s.stats.carries/s.games],['Rushing yards / game',s=>s.stats.rushing_yards==null?null:s.stats.rushing_yards/s.games],['Passing yards / game',s=>s.stats.passing_yards==null?null:s.stats.passing_yards/s.games],['Target share',s=>s.stats.target_share==null?null:s.stats.target_share*100],['Receiving EPA / game',s=>s.stats.receiving_epa==null?null:s.stats.receiving_epa/s.games]];
 return <><div className="tool-intro"><h2>Different eras. A common lens.</h2><p>Compare up to four player-seasons. Match age or career stage, then inspect production and opportunity.</p></div><div className="history-layout"><section className="tool-card"><div className="section-heading"><h3>Find a player-season</h3><Choice label="Season" value={season} onChange={setSeason} options={Array.from({length:manifest.season-manifest.firstSeason+1},(_,i)=>[String(manifest.season-i),String(manifest.season-i)])}/></div><div className="search-field wide"><Search size={16}/><Input aria-label="Search historical players" value={q} onChange={e=>setQ(e.target.value)} placeholder="Try Jerry Rice or LaDainian Tomlinson"/></div><Choice label="Match first selection" value={mode} onChange={setMode} options={[["all","All players"],["age","Same position + age (±1 year)"],["career","Same position + career year"]]}/>{error&&<p className="error" role="alert">{error}</p>}{busy?<p role="status">Loading season…</p>:<div className="candidate-list">{candidates.map(e=><button key={e.id} disabled={selected.length>=4||selected.some(s=>s.id===e.id&&s.season===e.season)} onClick={()=>add(e)}><div><strong>{e.name}</strong><small><Pos p={e.position}/> {e.team} · Age {fmt(e.age)} · {fmt(points(e.stats,e.position,config)/e.games)} PPG</small></div><Plus size={16}/></button>)}{!candidates.length&&<p>No matching player-seasons.</p>}</div>}</section><section className="tool-card comparison"><div className="section-heading"><h3>Side by side</h3><span className="muted">{selected.length} / 4</span></div>{!selected.length?<div className="empty-state">Choose a player-season to start comparing.</div>:<><div className="comparison-cards">{selected.map((s,i)=><div key={`${s.id}-${s.season}`} style={{borderTopColor:['#87a958','#657fa9','#bf8a62','#748f85'][i]}}><button aria-label={`Remove ${s.name} ${s.season}`} onClick={()=>setSelected(selected.filter(e=>e!==s))}><X size={14}/></button><small>{s.season} · {s.team}</small><strong>{s.name}</strong><span>{fmt(points(s.stats,s.position,config)/s.games)}<small>points / game</small></span></div>)}</div><Table><TableHeader><TableRow><TableHead>Metric</TableHead>{selected.map(s=><TableHead key={`${s.id}-${s.season}`}>{s.name.split(' ').at(-1)} ’{String(s.season).slice(2)}</TableHead>)}</TableRow></TableHeader><TableBody>{metrics.map(([name,get])=><TableRow key={name}><TableCell>{name}</TableCell>{selected.map(s=><TableCell key={`${s.id}-${s.season}`}>{fmt(get(s))}</TableCell>)}</TableRow>)}</TableBody></Table><p className="chart-caption">Percentile is within the position and season using standard PPR. Partial seasons, small samples, and zero-stat appearances can affect comparisons. “—” means unavailable.</p></>}</section></div></>;
}
