'use client';
import { useMemo,useState } from 'react';
import { ArrowRight,RefreshCw,Shield } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Table,TableBody,TableCell,TableHead,TableHeader,TableRow } from '@/components/ui/table';
import { type Config,type RankedPlayer,positions } from '@/lib/football';
import { api,Choice,fmt,Pos } from './ui-support';
export interface LeagueData {league:{league_id:string;name:string;season:string;total_rosters:number;roster_positions:string[];settings?:Record<string,unknown>};rosters:{roster_id:number;owner_id:string|null;players:string[]|null;reserve?:string[]|null;taxi?:string[]|null}[];users:{user_id:string;display_name:string;metadata?:{team_name?:string}}[];tradedPicks:{season:string;round:number;roster_id:number;owner_id:number;previous_owner_id:number}[];drafts:{draft_id:string;status:string;season:string;type:string}[];config:Config;warnings:string[];notes?:string[];fetchedAt:string}
export function rosterName(league:LeagueData,id:number){const roster=league.rosters.find(r=>r.roster_id===id),user=league.users.find(u=>u.user_id===roster?.owner_id);return user?.metadata?.team_name??user?.display_name??`Roster ${id}`;}
export function League({league,onLeague,ranked,season,onPlayer}:{league:LeagueData|null;onLeague:(l:LeagueData)=>void;ranked:RankedPlayer[];season:number;onPlayer:(p:RankedPlayer)=>void}){
 const [query,setQuery]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[choices,setChoices]=useState<{league_id:string;name:string}[]>([]),[roster,setRoster]=useState('');
 async function connect(value=query){setBusy(true);setError('');try{const d=await api<LeagueData|{leagues:{league_id:string;name:string}[]}>('/api/league',{query:value,season});if('leagues'in d){setChoices(d.leagues);if(!d.leagues.length)setError(`No ${season} NFL leagues found for this username.`);}else{onLeague(d);setRoster(String(d.rosters[0]?.roster_id??''));setChoices([]);}}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const rosterId=Number(roster||league?.rosters[0]?.roster_id),selected=league?.rosters.find(r=>r.roster_id===rosterId),owned=new Set(selected?.players??[]),allOwned=new Set(league?.rosters.flatMap(r=>r.players??[])??[]);
 const team=ranked.filter(p=>owned.has(p.sleeperId)),available=ranked.filter(p=>!allOwned.has(p.sleeperId));
 const unmapped=(selected?.players??[]).filter(id=>!ranked.some(p=>p.sleeperId===id));
 const strength=useMemo(()=>positions.map(pos=>({pos,value:team.filter(p=>p.position===pos).reduce((s,p)=>s+p.value,0),count:team.filter(p=>p.position===pos).length})),[team]);
 return <><section className="connect-card"><div className="connect-icon"><Shield/></div><div><h2>Your league changes the numbers.</h2><p>Import scoring, rosters, and traded picks from Sleeper. No Sleeper password required.</p><form onSubmit={e=>{e.preventDefault();void connect();}} className="connect-form"><Input aria-label="Sleeper username or league ID" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Sleeper username or league ID" required/><Button disabled={busy}>{busy?'Connecting…':'Connect league'}<ArrowRight size={16}/></Button></form><small>Read-only public league lookup. This does not authenticate you as a league member.</small></div></section>{error&&<p role="alert" className="error">{error}</p>}{choices.length>0&&<div className="league-choices">{choices.map(l=><Button key={l.league_id} variant="outline" onClick={()=>connect(l.league_id)}>{l.name}<ArrowRight size={14}/></Button>)}</div>}
 {league&&<><div className="section-heading"><div><div className="eyebrow">CONNECTED LEAGUE</div><h2>{league.league.name}</h2><p className="muted">{league.league.total_rosters} teams · {league.league.season} · Synced {new Date(league.fetchedAt).toLocaleString()}</p></div><Button variant="outline" disabled={busy} onClick={()=>connect(league.league.league_id)}><RefreshCw size={14}/>Refresh</Button></div><p className="chart-caption">League snapshots are cached for five minutes. Refresh uses that cache to protect the upstream API.</p>{league.notes?.map(n=><p className="chart-caption" key={n}>{n}</p>)}{league.warnings.map(w=><p className="notice" key={w}>{w}</p>)}<div className="settings-row"><Choice label="Roster" value={String(rosterId)} onChange={setRoster} options={league.rosters.map(r=>[String(r.roster_id),rosterName(league,r.roster_id)])}/></div><div className="strength-grid">{strength.map(s=><div className="tool-card" key={s.pos}><Pos p={s.pos}/><strong>{fmt(s.value,0)}</strong><small>trade-value units · {s.count} players</small></div>)}</div><div className="two-columns"><section className="tool-card"><h3>Roster overview</h3>{!team.length?<p>No supported offensive players found.</p>:<Table><TableHeader><TableRow><TableHead>Player</TableHead><TableHead>Rating</TableHead><TableHead>PPG</TableHead></TableRow></TableHeader><TableBody>{team.map(p=><TableRow key={p.id}><TableCell><button onClick={()=>onPlayer(p)}>{p.name} <Pos p={p.position}/></button></TableCell><TableCell>{fmt(p.rating)}</TableCell><TableCell>{fmt(p.ppg)}</TableCell></TableRow>)}</TableBody></Table>}{unmapped.length>0&&<p className="notice">{unmapped.length} roster entries have unsupported positions or no catalog record. IDs: {unmapped.join(', ')}.</p>}</section><section className="tool-card"><h3>Best available</h3><p className="muted">Unrostered players under your league’s scoring.</p><div className="candidate-list">{available.slice(0,12).map(p=><button key={p.id} onClick={()=>onPlayer(p)}><div><strong>{p.name}</strong><small><Pos p={p.position}/> {p.team} · {fmt(p.ppg)} projected PPG</small></div><b>{fmt(p.rating)}</b></button>)}</div></section></div><section className="tool-card"><h3>Traded rookie picks</h3>{!league.tradedPicks.length?<p className="muted">No traded picks recorded.</p>:<Table><TableHeader><TableRow><TableHead>Draft</TableHead><TableHead>Round</TableHead><TableHead>Original owner</TableHead><TableHead>Current owner</TableHead></TableRow></TableHeader><TableBody>{league.tradedPicks.map(p=><TableRow key={`${p.season}-${p.round}-${p.roster_id}`}><TableCell>{p.season}</TableCell><TableCell>{p.round}</TableCell><TableCell>{rosterName(league,p.roster_id)}</TableCell><TableCell>{rosterName(league,p.owner_id)}</TableCell></TableRow>)}</TableBody></Table>}</section></>}
 </>;
}
