'use client';
import { useEffect,useState } from 'react';
import { Sheet,SheetContent,SheetTitle,SheetDescription } from '@/components/ui/sheet';
import { Table,TableBody,TableCell,TableHead,TableHeader,TableRow } from '@/components/ui/table';
import { Button } from '@/components/ui/button';
import { type RankedPlayer,type PlayerDetail,type Config,points } from '@/lib/football';
import { Choice,fmt,Pos,api } from './ui-support';
import { Spread } from './scoring-spread';
export function Profile({player,config,onClose,onCompare}:{player:RankedPlayer|null;config:Config;onClose:()=>void;onCompare:(id:string,season:number)=>void}){
 const [detail,setDetail]=useState<PlayerDetail|null>(null),[error,setError]=useState(''),[season,setSeason]=useState('');
 const [ratings,setRatings]=useState<{rating:string;value:string;recorded_at:string;snapshot_id:string;model_version?:string}[]>([]);
 useEffect(()=>{setRatings([]);if(!player)return;const c=new AbortController();api<{history:typeof ratings}>(`/api/player/${encodeURIComponent(player.id)}/ratings`,undefined,c.signal).then(d=>setRatings(d.history)).catch(()=>{});return()=>c.abort();},[player?.id]);
 useEffect(()=>{setDetail(null);setError('');if(!player)return;const c=new AbortController();api<PlayerDetail>(`/api/player/${encodeURIComponent(player.id)}`,undefined,c.signal).then(d=>{setDetail(d);setSeason(String(d.seasons.at(-1)?.season??''));}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[player?.id]);
 const games=detail?.weekly.filter(g=>String(g.season)===season)??[];
 const scores=games.map(g=>points(g.stats,player?.position??'WR',config));const max=Math.max(1,...scores);
 const seasonStats=detail?.seasons.find(s=>String(s.season)===season);
 return <Sheet open={!!player} onOpenChange={open=>{if(!open)onClose();}}><SheetContent className="profile-sheet">{player&&<><div className="eyebrow">PLAYER RESEARCH · {player.position}{player.positionRank}</div><SheetTitle className="profile-title">{player.name}</SheetTitle><SheetDescription><Pos p={player.position}/> {player.team} · Age {fmt(player.age)} · {player.status}</SheetDescription><div className="profile-rating">{fmt(player.rating)}<small>QUANT RATING / 100</small></div><div className="metric-grid"><div><small>Projected PPG</small><strong>{fmt(player.ppg)}</strong></div><div><small>Rest of season</small><strong>{fmt(player.rosPoints)}</strong></div><div><small>Next game {player.nextOpponent?`vs ${player.nextOpponent}`:''}</small><strong>{fmt(player.nextGamePoints)}</strong></div><div><small>Underlying trade value</small><strong>{fmt(player.value,0)}</strong></div></div><h3>Scoring spread</h3><Spread spread={player.spread}/><p className="chart-caption">Median ± 1 sample SD · latest 17 statistical appearances · selected scoring. Not a prediction interval.</p><h3>Inside the rating</h3>{player.explanation.map(e=><p className="explanation" key={e}>{e}</p>)}<p className="notice">{player.confidence} confidence · {player.mapping==='unmatched'?'No confirmed historical identity match. ':''}Status observed {new Date(player.statusAsOf).toLocaleDateString()}. Availability is not injury-adjusted.</p>
 {error&&<p className="error" role="alert">{error}</p>}{!detail&&!error&&<p role="status">Loading player history…</p>}
 {detail&&<><div className="section-heading"><h3>Weekly production</h3>{detail.seasons.length>0&&<Choice label="Season" value={season} onChange={setSeason} options={detail.seasons.map(s=>[String(s.season),String(s.season)]).reverse() as [string,string][]}/>}</div>{!games.length?<p className="muted">No matched NFL statistics yet. Forecasts use disclosed priors.</p>:<><div className="weekly-chart" role="img" aria-label={`Weekly fantasy scores for ${player.name} in ${season}: ${games.map((g,i)=>`week ${g.week} ${fmt(scores[i])}`).join(', ')}`}>{games.map((g,i)=><div key={g.week}><span>{fmt(scores[i])}</span><i style={{height:`${Math.max(3,scores[i]/max*120)}px`}}/><small>{g.week}</small></div>)}</div><p className="chart-caption">Fantasy points under selected scoring · weeks with statistical appearances</p></>}
 {seasonStats&&<><h3>{season} opportunity & efficiency</h3><div className="compact-table"><Table><TableHeader><TableRow><TableHead>Statistic</TableHead><TableHead>Season total</TableHead><TableHead>Per game</TableHead></TableRow></TableHeader><TableBody>{[['targets','Targets'],['receptions','Receptions'],['receiving_yards','Receiving yards'],['receiving_tds','Receiving TDs'],['carries','Carries'],['rushing_yards','Rushing yards'],['rushing_tds','Rushing TDs'],['passing_yards','Passing yards'],['passing_tds','Passing TDs'],['passing_interceptions','Interceptions'],['receiving_air_yards','Air yards'],['receiving_yards_after_catch','Yards after catch'],['receiving_epa','Receiving EPA'],['rushing_epa','Rushing EPA'],['passing_epa','Passing EPA']].map(([key,label])=><TableRow key={key}><TableCell>{label}</TableCell><TableCell>{fmt(seasonStats.stats[key])}</TableCell><TableCell>{seasonStats.stats[key]==null?'—':fmt(seasonStats.stats[key]!/seasonStats.games)}</TableCell></TableRow>)}</TableBody></Table></div><p className="chart-caption">Average target share: {seasonStats.stats.target_share==null?'unavailable':`${fmt(seasonStats.stats.target_share*100)}%`} · Yards per target: {seasonStats.stats.targets?fmt((seasonStats.stats.receiving_yards??0)/seasonStats.stats.targets):'—'}</p></>}
 <h3>Season history</h3><div className="compact-table"><Table><TableHeader><TableRow><TableHead>Season</TableHead><TableHead>Team</TableHead><TableHead>Games*</TableHead><TableHead>Points / game</TableHead><TableHead/></TableRow></TableHeader><TableBody>{[...detail.seasons].sort((a,b)=>b.season-a.season).map(s=><TableRow key={s.season}><TableCell>{s.season}</TableCell><TableCell>{s.team}</TableCell><TableCell>{s.games}</TableCell><TableCell>{fmt(points(s.stats,s.position,config)/s.games)}</TableCell><TableCell><Button variant="ghost" onClick={()=>onCompare(s.id,s.season)}>Compare</Button></TableCell></TableRow>)}</TableBody></Table></div><p className="chart-caption">*Statistical appearances; zero-stat appearances may be absent. Missing metrics are not zero.</p>
 <h3>Rating history</h3>{ratings.length>0?<><p className="chart-caption">Archived publication values: 12-team, 1QB, PPR, no TE premium.</p><Table><TableHeader><TableRow><TableHead>Published / model</TableHead><TableHead>Rating</TableHead><TableHead>Value</TableHead></TableRow></TableHeader><TableBody>{ratings.map(r=><TableRow key={r.snapshot_id}><TableCell>{new Date(r.recorded_at).toLocaleDateString()}<small className="muted"> · {r.model_version??'legacy'}</small></TableCell><TableCell>{fmt(Number(r.rating))}</TableCell><TableCell>{fmt(Number(r.value),0)}</TableCell></TableRow>)}</TableBody></Table></>:<p className="muted">Archived rating snapshots will appear after pipeline publication. Last-game change is a recomputation with the latest game removed, not an archived historical rating.</p>}</>}
 </>}</SheetContent></Sheet>;
}
