'use client';
import { useEffect, useMemo, useState } from 'react';
import { flushSync } from 'react-dom';
import { ArrowDownUp, ArrowUpRight, Activity, ChartNoAxesCombined, ChevronRight, CircleHelp, GitCompareArrows, Layers3, Search, Shield, SlidersHorizontal, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { type Dataset, type RankedPlayer, defaultConfig, positions, rankPlayers } from '@/lib/football';

import { Choice,Pos,fmt,api } from './ui-support';
import { Profile } from './profile';
import { History } from './history';
import { League,type LeagueData } from './league';
import { Trade } from './trade';
export function Workbench({dataset:initialDataset}:{dataset:Dataset}){
  const [dataset,setDataset]=useState(initialDataset),[view,setView]=useState('rankings'),[league,setLeague]=useState<LeagueData|null>(null),[compare,setCompare]=useState<{id:string;season:number}|null>(null),[dataWarning,setDataWarning]=useState('');
  useEffect(()=>{const c=new AbortController();api<Dataset>('/api/catalog',undefined,c.signal).then(setDataset).catch(e=>{if(!c.signal.aborted)setDataWarning('Live snapshot unavailable. Showing the bundled, timestamped dataset.');});return()=>c.abort();},[]);
  const [config,setConfig]=useState(defaultConfig),[query,setQuery]=useState(''),[position,setPosition]=useState('ALL'),[selected,setSelected]=useState<RankedPlayer|null>(null),[limit,setLimit]=useState(50),[sort,setSort]=useState<'value'|'form'|'ppg'>('value');
  const ranked=useMemo(()=>rankPlayers(dataset.players,config),[dataset.players,config]);
  useEffect(()=>{
    const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;
    if(!context)return;const lifecycle=new AbortController();
    void Promise.resolve(context.registerTool({name:'filter_ffquant_rankings',title:'Filter FFQuant rankings',description:'Show the dynasty rankings filtered by player name and position. Changes the visible filters only.',inputSchema:{type:'object',properties:{query:{type:'string',maxLength:80},position:{type:'string',enum:['ALL','QB','RB','WR','TE']}},required:['query','position'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute(input:unknown){const x=input as {query?:unknown;position?:unknown};if(!x||typeof x.query!=='string'||x.query.length>80||typeof x.position!=='string'||!['ALL','QB','RB','WR','TE'].includes(x.position))throw new Error('Invalid ranking filters.');flushSync(()=>{setView('rankings');setQuery(x.query as string);setPosition(x.position as string);setLimit(50);});return {query:x.query,position:x.position,matches:ranked.filter(p=>(x.position==='ALL'||p.position===x.position)&&`${p.name} ${p.team}`.toLowerCase().includes((x.query as string).toLowerCase())).length};}},{signal:lifecycle.signal})).catch(()=>{});
    return()=>lifecycle.abort();
  },[ranked]);
  const filtered=useMemo(()=>ranked.filter(p=>(position==='ALL'||p.position===position)&&`${p.name} ${p.team}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='form'?(b.currentForm??-999)-(a.currentForm??-999):sort==='ppg'?b.ppg-a.ppg:b.value-a.value),[ranked,position,query,sort]);
  const m=dataset.manifest;
  return <div className="app-shell"><aside className="rail"><a className="brand" href="/"><span className="brand-mark">F<span>↗</span></span><span>FF<span className="brand-light">Quant</span><small>FANTASY FOOTBALL RESEARCH</small></span></a><div className="rail-label">WORKSPACE</div><nav>{[['rankings','Dynasty rankings',ChartNoAxesCombined],['trade','Trade calculator',GitCompareArrows],['history','Historical lab',Layers3],['league','My league',Shield],['method','Model & sources',CircleHelp]].map(([id,label,Icon])=>{const I=Icon as typeof Shield;return <Button key={String(id)} aria-label={String(label)} className={`nav-item ${view===id?'active':''}`} variant="ghost" onClick={()=>setView(String(id))}><I/>{String(label)}{view===id&&<ChevronRight/>}</Button>;})}</nav><div className="rail-bottom"><div className="beta-tag"><span/> RESEARCH BETA</div><p>Football performance.<br/>A longer perspective.</p><div className="rail-foot">INDEPENDENT · NON-COMMERCIAL</div></div></aside>
  <div className="workspace"><header className="topbar"><div className="breadcrumb">Workspace <ChevronRight size={14}/><strong>{({rankings:'Dynasty rankings',trade:'Trade calculator',history:'Historical lab',league:'My league',method:'Model & sources'} as Record<string,string>)[view]}</strong></div><div className="season-indicator"><span className="live-dot"/>{m.season} SEASON <span className="divider">/</span> WEEK {m.week}</div></header><main id="main-content"><div className="page-title"><div><div className="eyebrow">THE LONG GAME, QUANTIFIED</div><h1>{({rankings:'Dynasty rankings',trade:'Trade calculator',history:'Historical lab',league:'My league',method:'Model & sources'} as Record<string,string>)[view]}<span>.</span></h1><p>Find the production behind the price.</p></div><div className="title-note"><Activity size={16}/><div>Performance-driven model<small>Experimental · {m.modelVersion}</small></div></div></div>
  {dataWarning&&<p className="notice" role="status">{dataWarning}</p>}{(Date.now()-new Date(m.sourceUpdatedAt).getTime())/36e5>36&&<p className="notice">Statistics are more than 36 hours old. This is a historical snapshot, not live scoring.</p>}<section className="market-strip" aria-label="Dataset overview"><div><small>PLAYER UNIVERSE</small><strong>{m.playerCount.toLocaleString()}<span>Sleeper player pool</span></strong></div><div><small>HISTORICAL COVERAGE</small><strong>{m.firstSeason}—{m.season}<span>{m.season-m.firstSeason+1} seasons</span></strong></div><div><small>VALUATION HORIZON</small><strong>3 seasons<span>production + potential</span></strong></div><div className="strip-source"><small>STATISTICS UPDATED</small><strong>{new Date(m.sourceUpdatedAt).toLocaleDateString('en-US',{month:'short',day:'numeric',timeZone:'America/New_York'})}<span>nflverse · Sleeper</span></strong></div></section>
  {view!=='league'&&view!=='method'&&<div className="settings-row"><div className="settings-caption"><SlidersHorizontal size={16}/> League settings</div><Choice label="Format" value={config.superflex?'sf':'1qb'} onChange={v=>setConfig({...config,scoring:undefined,slots:undefined,superflex:v==='sf'})} options={[["1qb","1 QB"],["sf","Superflex"]]}/><Choice label="Scoring" value={String(config.ppr)} onChange={v=>setConfig({...config,scoring:undefined,slots:undefined,ppr:Number(v)})} options={[["0","Standard"],["0.5","Half PPR"],["1","PPR"]]}/><Choice label="Teams" value={String(config.teams)} onChange={v=>setConfig({...config,scoring:undefined,slots:undefined,teams:Number(v)})} options={[8,10,12,14,16].map(v=>[String(v),String(v)])}/><Choice label="TE premium" value={String(config.tep)} onChange={v=>setConfig({...config,scoring:undefined,slots:undefined,tep:Number(v)})} options={[["0","None"],["0.5","+0.5 / catch"],["1","+1 / catch"]]}/>{league&&<Button variant="outline" onClick={()=>setConfig(league.config)}>Use {league.league.name}</Button>}</div>}
  {league&&JSON.stringify(config)===JSON.stringify(league.config)&&league.warnings.map(w=><p className="notice" key={w}>{w}</p>)}{view==='rankings'&&<><section className="rankings-panel"><div className="table-toolbar"><div className="position-tabs" aria-label="Filter position">{['ALL',...positions].map(p=><Button key={p} variant="ghost" aria-pressed={position===p} className={position===p?'selected':''} onClick={()=>{setPosition(p);setLimit(50);}}>{p==='ALL'?'All players':p}</Button>)}</div><div className="search-field"><Search size={16}/><Input aria-label="Search players" placeholder="Search player or team" value={query} onChange={e=>{setQuery(e.target.value);setLimit(50);}}/></div></div>
  <Table><TableHeader><TableRow><TableHead className="rank-cell">RK</TableHead><TableHead>PLAYER</TableHead><TableHead>AGE</TableHead><TableHead><button onClick={()=>setSort('value')}>QUANT RATING <ArrowDownUp size={12}/></button></TableHead><TableHead>LAST GAME Δ</TableHead><TableHead><button onClick={()=>setSort('form')}>CURRENT FORM <ArrowDownUp size={12}/></button></TableHead><TableHead><button onClick={()=>setSort('ppg')}>PROJ. PPG <ArrowDownUp size={12}/></button></TableHead><TableHead/></TableRow></TableHeader><TableBody>{filtered.slice(0,limit).map(p=><TableRow key={p.id}><TableCell className="rank-cell">{String(p.rank).padStart(2,'0')}</TableCell><TableCell><button className="player-name" onClick={()=>setSelected(p)}><span className={`avatar avatar-${p.position}`}>{p.name.split(' ').map(n=>n[0]).slice(0,2).join('')}</span><span><strong>{p.name}</strong><small><Pos p={p.position}/>{p.team}<span className="subtle-separator">·</span>{p.position}{p.positionRank}{p.confidence==='low'&&<span className="prior-label">Prior-led</span>}</small></span></button></TableCell><TableCell className="muted">{fmt(p.age)}</TableCell><TableCell><div className="rating-cell"><strong>{fmt(p.rating)}</strong><span className="rating-track"><i style={{width:`${p.rating}%`}}/></span></div></TableCell><TableCell><span className={p.change!=null&&p.change>=0?'positive':'negative'}>{p.change==null?'—':`${p.change>=0?'+':''}${fmt(p.change)}`}</span></TableCell><TableCell><span className={`form-cell ${(p.currentForm??0)>=0?'positive':'negative'}`}>{p.currentForm==null?'—':`${p.currentForm>=0?'+':''}${fmt(p.currentForm)} pts`}<span className="form-bars" aria-hidden="true">{[.35,.65,.45,.8,1].map((v,i)=><i key={i} style={{height:Math.max(3,Math.min(20,Math.abs(p.currentForm??0)*2)*v)}}/>)}</span></span></TableCell><TableCell className="ppg">{fmt(p.ppg)}</TableCell><TableCell><Button variant="ghost" size="icon" aria-label={`View ${p.name}`} onClick={()=>setSelected(p)}><ArrowUpRight size={16}/></Button></TableCell></TableRow>)}</TableBody></Table>
  {!filtered.length&&<div className="empty-state">No players match this search.</div>}<div className="table-footer"><span>Showing {Math.min(limit,filtered.length)} of {filtered.length} players</span>{limit<filtered.length&&<Button variant="outline" onClick={()=>setLimit(limit+50)}>Show 50 more</Button>}<span>Ratings are nonlinear. Never add them together.</span></div></section><div className="research-note"><CircleHelp size={17}/><p><strong>Built to be questioned.</strong> Ratings are experimental estimates of future production above replacement. Current form measures recent PPR production versus a historical baseline. Last-game change is a counterfactual under today’s settings.</p></div></>}
  {view==='history'&&<History config={config} manifest={m} initial={compare}/>}
  {view==='league'&&<League league={league} onLeague={l=>{setLeague(l);setConfig(l.config);}} ranked={ranked} season={m.season} onPlayer={setSelected}/>}
  {view==='trade'&&<Trade key={JSON.stringify(config)+league?.league.league_id} ranked={ranked} config={config} firstDraft={m.season+(m.week>0?1:0)} league={league}/>}
  {view==='method'&&<section className="tool-card methodology"><div className="eyebrow">BASELINE 0.1 · EXPERIMENTAL</div><h2>Performance first. Assumptions visible.</h2><p>The official baseline estimates production from recent NFL statistics, shrinks small samples toward prior seasons, then values production above replacement over the remainder of this season and two future seasons. Future seasons are discounted by 15% per year.</p><h3>The 1–100 scale</h3><p>Ratings are a logarithmic display of underlying value. A 100 is worth far more than fifty 2s. Trades use unrounded values plus roster costs and replacements. The scale is anchored to a model version, not the best player each day.</p><h3>What changes a rating?</h3><p>Recent volume and efficiency, position, age, draft priors, scoring, and lineup scarcity. Opponent effects are bounded to ±10% and applied to the next-game forecast, not dynasty value. Current-form figures use PPR consistently; projections use your selected scoring.</p><h3>What is not known yet?</h3>{m.limitations.map(l=><p key={l} className="explanation">{l}</p>)}<p>Availability is not modeled from live injury reports. Snap and route metrics are omitted where unavailable. Team roles are reflected in observed usage, not verified future depth charts. Regression and boosted-tree experiments remain owner-only and cannot replace the baseline without review.</p><h3>Data provenance</h3><p>Snapshot <code>{m.id}</code><br/>Built {new Date(m.builtAt).toLocaleString()}<br/>Statistics updated {new Date(m.sourceUpdatedAt).toLocaleString()}<br/>{m.unmatchedCount} active catalog records lack a confirmed historical identity and use priors.</p><p><a href="https://github.com/nflverse/nflverse-data/blob/main/LICENSE.md">nflverse · CC BY 4.0</a> · <a href="https://docs.sleeper.com/">Sleeper · non-commercial API</a> · <a href="https://github.com/DynastyProcess/data">DynastyProcess player IDs</a></p><p>Derived and reformatted statistics are our own transformations. No affiliation with the NFL, Sleeper, or the data providers is implied.</p><h3>Historical coverage</h3><div className="coverage-grid">{m.coverage.map(c=><div key={c.season}><strong>{c.season}</strong><span>{c.players} players · {c.rows.toLocaleString()} weekly rows</span></div>)}</div><h3>Current source files</h3><ul>{m.sources.filter(s=>!s.url.includes('stats_player_week_')||s.url.includes(String(m.season))).map(s=><li key={s.url}><a href={s.url}>{s.url.split('/').at(-1)}</a><small> · Retrieved {new Date(s.fetchedAt).toLocaleDateString()}</small></li>)}</ul></section>}
  <footer className="page-footer"><span>FFQUANT <span>© {m.season}</span></span><span>Statistics: <a href="https://nflverse.nflverse.com/">nflverse</a> · League data: <a href="https://docs.sleeper.com/">Sleeper</a></span></footer>
  </main></div><Profile player={selected?ranked.find(p=>p.id===selected.id)??selected:null} config={config} onClose={()=>setSelected(null)} onCompare={(id,season)=>{setCompare({id,season});setSelected(null);setView('history');}}/></div>;
}
